### ISSUE TITLE
D3D12SerializeVersionedRootSignature “One or more arguments are invalid.”

### ISSUE THREAD

**Issue by Zachary-Zuo** [KaiH0717/Kaguya#2]
Hello.
I was able to compile without any problems, but when running(D3D12rootSignature.cpp Line 200)
"HRESULT Result = D3D12SerializeVersionedRootSignature(&ApiDesc, &SerializedRootSignatureBlob, &ErrorBlob);"
An exception is thrown and the content of the ErrorBlob is "E_INVALIDARG One or more arguments are invalid."
Do you know the possible cause of the error, my development environment is CMake 3.24, VS2022, Windows 10, 2080Ti

**Comment by kcloudy0717** [comment]
Hey Zachary, can you share which root signature creation is giving you an error?

**Comment by Zachary-Zuo** [comment]
> Hey Zachary, can you share which root signature creation is giving you an error?

The PostProcess in the initialization list of the PathIntegratorDXR1_1 class calls during initialization
PostProcessRS = Device->CreateRootSignature(RHI::RootSignatureDesc().AddConstantBufferView(0, 0));

**Comment by Zachary-Zuo** [comment]
> Hey Zachary, can you share which root signature creation is giving you an error?

The PostProcess in the initialization list of the PathIntegratorDXR1_1 class calls during initialization
PostProcessRS = Device->CreateRootSignature(RHI::RootSignatureDesc().AddConstantBufferView(0, 0));

**Comment by kcloudy0717** [comment]
Hmm, this is quite odd, I'm on Windows 11 and this is not giving me an error, what is your Windows 10 version? Does it support Agility SDK? The project uses Agility SDK and the OS Version that supports Agility SDK must be greater than 1909
![image](https://user-images.githubusercontent.com/47328809/181298020-1b05cef4-66aa-45c8-adac-6ebc6bf79419.png)

**Comment by Zachary-Zuo** [comment]
This is indeed the cause of the problem. I have not updated the kernel version in place after reinstalling windows, thank you for your answer.
